#From Google Translate.

  #############################
 # durability value notation #
#############################
#Default
# Durability: 100 / 100

#Number
# 100 / 100

#Japanese
# 耐久値 : 100"／100

#Bar
# ■■■■■■■■■■

displayLore: "Default"